# Generated by Django 3.2.5 on 2021-07-08 14:09

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[myapp.models.validate_number]),
        ),
    ]
